[tool.poetry]
name = "pythonProject"
version = "0.1.0"
description = ""
authors = ["thoubou <thoubou@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.9"
torch = "^2.5.1"
torchvision = "^0.20.1"
flwr-datasets = "^0.4.0"
scipy = "^1.15.1"
statsmodels = "^0.14.4"
flask = "^3.1.0"
grpcio = "^1.71.0"
protobuf = "5.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
