# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_example/aggregator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_example/aggregator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgrpc_example/aggregator.proto\x12\naggregator\"P\n\x03\x41gg\x12\x14\n\x0coperation_id\x18\x01 \x01(\x05\x12\x10\n\x08\x61gg_func\x18\x02 \x01(\t\x12\x11\n\tagg_round\x18\x03 \x01(\x05\x12\x0e\n\x06values\x18\x04 \x03(\x01\"\x1d\n\x0b\x41ggResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\x01\x32M\n\nAggregator\x12?\n\x11GetServerResponse\x12\x0f.aggregator.Agg\x1a\x17.aggregator.AggResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_example.aggregator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGG']._serialized_start=45
  _globals['_AGG']._serialized_end=125
  _globals['_AGGRESPONSE']._serialized_start=127
  _globals['_AGGRESPONSE']._serialized_end=156
  _globals['_AGGREGATOR']._serialized_start=158
  _globals['_AGGREGATOR']._serialized_end=235
# @@protoc_insertion_point(module_scope)
