syntax = "proto3";

package aggregator;

service Aggregator{
  // A simple RPC.
  //
  // Obtains the MessageResponse at a given position.
 rpc GetServerResponse(Agg) returns (AggResponse) {}
 rpc GetOperationId(Operation) returns (OperationResponse) {}
 rpc GetRandom(Random) returns (RandomResponse) {}
 rpc GetCategoryServerResponse(CategoryAgg) returns (CategoryAggResponse) {}
 rpc GetIntServerResponse(IntegerAgg) returns (IntegerAggResponse) {}
}

message Agg{
 int32  operation_id=1;
 string agg_func = 2;
 int32 agg_round = 3; // The id of the aggregation
 repeated double values = 4;  // List (vector) of double values
}

message AggResponse{
 repeated double answer = 1;
}

message CategoryAgg{
 int32  operation_id=1;
 string agg_func = 2;
 int32 agg_round = 3; // The id of the aggregation
 repeated string values = 4;  // List (vector) of string values
}

message CategoryAggResponse{
 repeated string answer = 1;
}

message IntegerAgg{
 int32  operation_id=1;
 string agg_func = 2;
 int32 agg_round = 3; // The id of the aggregation
 repeated int32 values = 4;  // List (vector) of string values
}

message IntegerAggResponse{
 repeated int32 answer = 1;
}

message Operation{
}

message OperationResponse{
 int32  operation_id = 1;
}

message Random{
 int32  operation_id=1;
 int32 agg_round = 2; // The id of the aggregation
 int32 size = 3;
}

message RandomResponse{
 repeated double answer = 1;
}