# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aggregator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'aggregator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ggregator.proto\x12\naggregator\"P\n\x03\x41gg\x12\x14\n\x0coperation_id\x18\x01 \x01(\x05\x12\x10\n\x08\x61gg_func\x18\x02 \x01(\t\x12\x11\n\tagg_round\x18\x03 \x01(\x05\x12\x0e\n\x06values\x18\x04 \x03(\x01\"\x1d\n\x0b\x41ggResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x03(\x01\"\x0b\n\tOperation\")\n\x11OperationResponse\x12\x14\n\x0coperation_id\x18\x01 \x01(\x05\"?\n\x06Random\x12\x14\n\x0coperation_id\x18\x01 \x01(\x05\x12\x11\n\tagg_round\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\" \n\x0eRandomResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x03(\x01\x32\xd6\x01\n\nAggregator\x12?\n\x11GetServerResponse\x12\x0f.aggregator.Agg\x1a\x17.aggregator.AggResponse\"\x00\x12H\n\x0eGetOperationId\x12\x15.aggregator.Operation\x1a\x1d.aggregator.OperationResponse\"\x00\x12=\n\tGetRandom\x12\x12.aggregator.Random\x1a\x1a.aggregator.RandomResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGG']._serialized_start=32
  _globals['_AGG']._serialized_end=112
  _globals['_AGGRESPONSE']._serialized_start=114
  _globals['_AGGRESPONSE']._serialized_end=143
  _globals['_OPERATION']._serialized_start=145
  _globals['_OPERATION']._serialized_end=156
  _globals['_OPERATIONRESPONSE']._serialized_start=158
  _globals['_OPERATIONRESPONSE']._serialized_end=199
  _globals['_RANDOM']._serialized_start=201
  _globals['_RANDOM']._serialized_end=264
  _globals['_RANDOMRESPONSE']._serialized_start=266
  _globals['_RANDOMRESPONSE']._serialized_end=298
  _globals['_AGGREGATOR']._serialized_start=301
  _globals['_AGGREGATOR']._serialized_end=515
# @@protoc_insertion_point(module_scope)
