# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mini_mip_system._grpc.aggregator_pb2 as aggregator__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in aggregator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AggregatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerResponse = channel.unary_unary(
                '/aggregator.Aggregator/GetServerResponse',
                request_serializer=aggregator__pb2.Agg.SerializeToString,
                response_deserializer=aggregator__pb2.AggResponse.FromString,
                _registered_method=True)
        self.GetOperationId = channel.unary_unary(
                '/aggregator.Aggregator/GetOperationId',
                request_serializer=aggregator__pb2.Operation.SerializeToString,
                response_deserializer=aggregator__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.GetRandom = channel.unary_unary(
                '/aggregator.Aggregator/GetRandom',
                request_serializer=aggregator__pb2.Random.SerializeToString,
                response_deserializer=aggregator__pb2.RandomResponse.FromString,
                _registered_method=True)
        self.GetCategoryServerResponse = channel.unary_unary(
                '/aggregator.Aggregator/GetCategoryServerResponse',
                request_serializer=aggregator__pb2.CategoryAgg.SerializeToString,
                response_deserializer=aggregator__pb2.CategoryAggResponse.FromString,
                _registered_method=True)
        self.GetIntServerResponse = channel.unary_unary(
                '/aggregator.Aggregator/GetIntServerResponse',
                request_serializer=aggregator__pb2.IntegerAgg.SerializeToString,
                response_deserializer=aggregator__pb2.IntegerAggResponse.FromString,
                _registered_method=True)


class AggregatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerResponse(self, request, context):
        """A simple RPC.

        Obtains the MessageResponse at a given position.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperationId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRandom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategoryServerResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntServerResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponse,
                    request_deserializer=aggregator__pb2.Agg.FromString,
                    response_serializer=aggregator__pb2.AggResponse.SerializeToString,
            ),
            'GetOperationId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperationId,
                    request_deserializer=aggregator__pb2.Operation.FromString,
                    response_serializer=aggregator__pb2.OperationResponse.SerializeToString,
            ),
            'GetRandom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRandom,
                    request_deserializer=aggregator__pb2.Random.FromString,
                    response_serializer=aggregator__pb2.RandomResponse.SerializeToString,
            ),
            'GetCategoryServerResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategoryServerResponse,
                    request_deserializer=aggregator__pb2.CategoryAgg.FromString,
                    response_serializer=aggregator__pb2.CategoryAggResponse.SerializeToString,
            ),
            'GetIntServerResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntServerResponse,
                    request_deserializer=aggregator__pb2.IntegerAgg.FromString,
                    response_serializer=aggregator__pb2.IntegerAggResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aggregator.Aggregator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aggregator.Aggregator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Aggregator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aggregator.Aggregator/GetServerResponse',
            aggregator__pb2.Agg.SerializeToString,
            aggregator__pb2.AggResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperationId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aggregator.Aggregator/GetOperationId',
            aggregator__pb2.Operation.SerializeToString,
            aggregator__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRandom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aggregator.Aggregator/GetRandom',
            aggregator__pb2.Random.SerializeToString,
            aggregator__pb2.RandomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategoryServerResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aggregator.Aggregator/GetCategoryServerResponse',
            aggregator__pb2.CategoryAgg.SerializeToString,
            aggregator__pb2.CategoryAggResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntServerResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aggregator.Aggregator/GetIntServerResponse',
            aggregator__pb2.IntegerAgg.SerializeToString,
            aggregator__pb2.IntegerAggResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
